In [20]:
import pandas as pd
import plotly.graph_objects as go
import yfinance as yf

tsla = yf.Ticker('TSLA')

tesla_data = tsla.history(period = 'max')
tesla_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-04 00:00:00-04:00,345.100006,345.600006,327.329987,332.049988,98912100,0.0,0.0
2025-06-05 00:00:00-04:00,322.489990,324.549988,273.209991,284.700012,287499800,0.0,0.0
2025-06-06 00:00:00-04:00,298.829987,305.500000,291.140015,295.140015,164747700,0.0,0.0
2025-06-09 00:00:00-04:00,285.959991,309.829987,281.850006,308.579987,140908900,0.0,0.0
2025-06-10 00:00:00-04:00,314.940002,327.829987,310.670013,326.089996,150429600,0.0,0.0

In [21]:
tesla_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [22]:
tesla_data.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-06-04 00:00:00-04:00,345.100006,345.600006,327.329987,332.049988,98912100,0.0,0.0
2025-06-05 00:00:00-04:00,322.489990,324.549988,273.209991,284.700012,287499800,0.0,0.0
2025-06-06 00:00:00-04:00,298.829987,305.500000,291.140015,295.140015,164747700,0.0,0.0
2025-06-09 00:00:00-04:00,285.959991,309.829987,281.850006,308.579987,140908900,0.0,0.0
2025-06-10 00:00:00-04:00,314.940002,327.829987,310.670013,326.089996,150429600,0.0,0.0

In [23]:
fig = go.Figure(data = go.Scatter(x=tesla_data.index, y=tesla_data['Close']))
fig.update_layout(title = 'TESLA STOCK FROM START TO TODAY')
fig.show()

In [24]:
from plotly.subplots import make_subplots
fig2 = make_subplots(specs=[[{'secondary_y': True}]])
fig2.add_trace(go.Scatter(x=tesla_data.index, y=tesla_data['Close'], name='Revenue'),secondary_y=False)
fig2.update_layout(title='Tesla Revenue Chart')
fig2.show()

In [25]:
Game_Stop = yf.Ticker('GME')
Game_Stop

yfinance.Ticker object <GME>

In [31]:
gme_data = Game_Stop.history(period = 'max')
gme_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658002,1.674834,8389600,0.0,0.0
2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-04 00:00:00-04:00,29.900000,30.969999,29.340000,29.950001,7314000,0.0,0.0
2025-06-05 00:00:00-04:00,29.809999,30.610001,29.230000,29.450001,6322800,0.0,0.0
2025-06-06 00:00:00-04:00,29.680000,30.000000,29.520000,29.580000,4379300,0.0,0.0
2025-06-09 00:00:00-04:00,29.920000,30.490000,29.450001,30.340000,5836200,0.0,0.0
2025-06-10 00:00:00-04:00,30.540001,30.600000,29.660000,30.150000,11407500,0.0,0.0

In [32]:
gme_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658002,1.674834,8389600,0.0,0.0
2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [33]:
gme_data.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-06-04 00:00:00-04:00,29.900000,30.969999,29.340000,29.950001,7314000,0.0,0.0
2025-06-05 00:00:00-04:00,29.809999,30.610001,29.230000,29.450001,6322800,0.0,0.0
2025-06-06 00:00:00-04:00,29.680000,30.000000,29.520000,29.580000,4379300,0.0,0.0
2025-06-09 00:00:00-04:00,29.920000,30.490000,29.450001,30.340000,5836200,0.0,0.0
2025-06-10 00:00:00-04:00,30.540001,30.600000,29.660000,30.150000,11407500,0.0,0.0

In [34]:
## Using Plotly library to get Gamestop Stock graph

gme_stock = go.Figure(data = go.Scatter(x=gme_data.index,y=gme_data['Close']))
gme_stock.update_layout(title = 'GAMESTOP STOCK FROM START TO TODAY')
gme_stock.show()